import { serve } from "https://deno.land/std@0.168.0/http/server.ts"
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.57.4"

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

serve(async (req) => {
  // Handle CORS preflight requests
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const supabaseAdmin = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? '',
      {
        auth: {
          autoRefreshToken: false,
          persistSession: false
        }
      }
    )

    // Get the Authorization header
    const authHeader = req.headers.get('Authorization')
    if (!authHeader) {
      throw new Error('No authorization header')
    }

    // Verify the user is authenticated and is an admin
    const token = authHeader.replace('Bearer ', '')
    const { data: { user }, error: authError } = await supabaseAdmin.auth.getUser(token)
    
    if (authError || !user) {
      throw new Error('Authentication failed')
    }

    // Check if user is admin
    const { data: profile, error: profileError } = await supabaseAdmin
      .from('perfis')
      .select('role')
      .eq('user_id', user.id)
      .single()
    
    if (profileError || profile?.role !== 'admin') {
      throw new Error('Not authorized - admin required')
    }

    const { userId } = await req.json()

    if (!userId) {
      throw new Error('Missing required field: userId')
    }

    console.log('Deleting coordinator:', { userId })

    // 1) Collect dependent data
    const { data: projects, error: projectsError } = await supabaseAdmin
      .from('projetos')
      .select('id')
      .eq('coordinator_id', userId)

    if (projectsError) throw projectsError

    const projectIds = (projects ?? []).map((p: { id: string }) => p.id)

    if (projectIds.length > 0) {
      // 1a) Delete attendance records linked via participations
      const { data: participations, error: participationsError } = await supabaseAdmin
        .from('participacoes_projeto')
        .select('id')
        .in('project_id', projectIds);
      if (participationsError) throw participationsError;

      const participationIds = (participations ?? []).map((pp: { id: string }) => pp.id);

      if (participationIds.length > 0) {
        const { error: attendanceDelError } = await supabaseAdmin
          .from('registros_presenca')
          .delete()
          .in('participation_id', participationIds);
        if (attendanceDelError) throw attendanceDelError;
      }

      // 1b) Delete participations
      const { error: ppDelError } = await supabaseAdmin
        .from('participacoes_projeto')
        .delete()
        .in('project_id', projectIds);
      if (ppDelError) throw ppDelError;

      // 1c) Delete reports linked to those projects
      const { error: reportsByProjectDelError } = await supabaseAdmin
        .from('relatorios')
        .delete()
        .in('project_id', projectIds);
      if (reportsByProjectDelError) throw reportsByProjectDelError;

      // 1d) Delete projects
      const { error: projectsDelError } = await supabaseAdmin
        .from('projetos')
        .delete()
        .in('id', projectIds);
      if (projectsDelError) throw projectsDelError;
    }

    // 2) Delete reports generated by this user (if any)
    const { error: reportsByUserDelError } = await supabaseAdmin
      .from('relatorios')
      .delete()
      .eq('generated_by', userId);
    if (reportsByUserDelError) throw reportsByUserDelError;

    // 3) Finally delete the auth user (profile will cascade)
    const { error: deleteError } = await supabaseAdmin.auth.admin.deleteUser(userId)

    if (deleteError) {
      console.error('Error deleting user:', deleteError)
      throw deleteError
    }

    console.log('User deleted successfully:', userId)

    return new Response(
      JSON.stringify({ 
        success: true,
        message: 'Coordinator deleted successfully'
      }),
      { 
        headers: { ...corsHeaders, 'Content-Type': 'application/json' } 
      }
    )

  } catch (error: any) {
    console.error('Error in delete-coordinator function:', error)
    return new Response(
      JSON.stringify({ 
        error: error?.message || 'An error occurred',
        success: false
      }),
      { 
        status: 400, 
        headers: { ...corsHeaders, 'Content-Type': 'application/json' } 
      }
    )
  }
})
