-- Inserir dados dos alunos na tabela estudantes
-- Usando ON CONFLICT para evitar duplicatas por matrícula

INSERT INTO public.estudantes (matricula, name, email, course) VALUES 
('389046', 'ANNA LAURA MARTINS DINIZ', 'annalaura@alu.ufc.br', 'CIV'),
('402466', 'ANTONIO VICTOR CAMINHA DA SILVA', 'caminhavictor@gmail.com', 'CIV'),
('397844', 'MICAEL DE SOUSA LINO', 'micaelsousaa69@gmail.com', 'CIV'),
('399981', 'THIAGO GONCALVES SANTANA', 'thiagogoncalvesgs@gmail.com', 'CIV'),
('415183', 'ERIC HENRIQUE DE LIMA', 'eric.ufc18@gmail.com', 'CIV'),
('409779', 'EUGENIO DOS SANTOS E SILVA', 'eugeniodossantosesilva@gmail.com', 'CIV'),
('415058', 'FRANCISCO EMERSON MARTINS DE ALMEIDA', 'fremersonmartins@alu.ufc.br', 'CIV'),
('427686', 'GUSTAVO ILLGNER PEREIRA DE OLIVEIRA', 'illgner1611@alu.ufc.br', 'CIV'),
('409277', 'JOCÁSSIA MARIA DE OLIVEIRA DE LIMA', 'jocassia@alu.ufc.br', 'CIV'),
('427785', 'KARINA RODRIGUES ALVES', 'karinarodrigues.alves@alu.ufc.br', 'CIV'),
('421747', 'LUCAS NAATY NOGUEIRA', 'l.naaty@outlook.com', 'CIV'),
('427655', 'MANUELA LUCIANE NOBRE AGUIAR', 'manu_nobreaguiar@hotmail.com', 'CIV'),
('429023', 'PHABLO GABRIEL FERNANDES DE CASTRO', 'phablogabrielfernandes@gmail.com', 'CIV'),
('431807', 'DAVI CASTRO DE ALENCAR', 'davialencar22@gmail.com', 'CIV'),
('470787', 'BRUNA ELIDA VIDAL OLIVEIRA', 'brunaelidavo@alu.ufc.br', 'CIV'),
('475709', 'DAISY DE SOUSA SIQUEIRA', 'daisy.ctbj@gmail.com', 'CIV'),
('433494', 'EDGAR BRUNO BENICIO DE FREITAS', 'edgarbrunobenicio@gmail.com', 'CIV'),
('470685', 'ESTELA LIMA DE OLIVEIRA', 'limaestela2016@gmail.com', 'CIV'),
('476418', 'FRANCISCA ANDREA DE SOUSA OLIVEIRA', 'andreassousa@alu.ufc.br', 'CIV'),
('434300', 'IKARO PINHEIRO', 'ikaro.pinheiro@gmail.com', 'CIV'),
('475378', 'JORHDANN DE OLIVEIRA ANDRADE', 'jorhdannoliveira@alu.ufc.br', 'CIV'),
('475501', 'KLIWEER EMMANUELLY DE OLIVEIRA PESSOA', 'kliweeroliveira@gmail.com', 'CIV'),
('478160', 'LIVIA FERNANDES DE MORAES', 'liviafmoraes@alu.ufc.br', 'CIV'),
('476632', 'MARCUS VINICIUS PEREIRA BEZERRA', 'marcusvinicius0205@alu.ufc.br', 'CIV'),
('470071', 'PEDRO LEVI SARAIVA', 'alunolevi@alu.ufc.br', 'CIV'),
('476041', 'RODOLFO MOREDISSON SILVA DE OLIVEIRA', 'Rodolfooliveirajj7@alu.ufc.br', 'CIV'),
('474277', 'VANESSA SAND COSTA CONRADO', 'vanessasand@alu.ufc.br', 'CIV'),
('475538', 'WILBER LIMA DO NASCIMENTO', 'wilberlima@alu.ufc.br', 'CIV'),
('495766', 'ALBER RYAN LIMA SANTOS', 'albersantos@alu.ufc.br', 'CIV'),
('499168', 'CARLOS HENRIQUE DA SILVA MORAIS', 'carloshenrique1698@alu.ufc.br', 'CIV'),
('484862', 'ELIAS VITOR CHAGAS GOMES', 'eliasvcg@alu.ufc.br', 'CIV'),
('498943', 'GUILHERME NUNES LOPES', 'guibol71@alu.ufc.br', 'CIV'),
('499394', 'HYAGO BRENO BARROS GADELHA', 'hyagobarros@alu.ufc.br', 'CIV'),
('497022', 'ISABELA GUILHEM BEZERRA DA SILVA', 'isabelaguilhemg@alu.ufc.br', 'CIV'),
('494021', 'KEREN PEREIRA LIMA', 'kerenpereiralima@alu.ufc.br', 'CIV'),
('500188', 'LARISSA DE FREITAS RABELO', 'laryssarabelo@alu.ufc.br', 'CIV'),
('496377', 'LIVIA CRISTINA LOPES SOUSA', 'liacristina2002@alu.ufc.br', 'CIV'),
('496950', 'MICHAEL JACKSON ALVES DE OLIVEIRA', 'mjackson20@alu.ufc.br', 'CIV'),
('497002', 'MOISES DA SILVA VALE', 'moisessilva9811@alu.ufc.br', 'CIV'),
('497103', 'RAUEY JONES SILVA PEREIRA', 'raueyjones2020@alu.ufc.br', 'CIV'),
('501064', 'REBECA DA SILVA FERREIRA', 'beca.silva@alu.ufc.br', 'CIV'),
('497487', 'THIAGO VIDAL MARTINS', 'thiagovidal09@alu.ufc.br', 'CIV'),
('497699', 'VYTORYA MARIA DA SILVA FREITAS', 'vytoryamsilva@alu.ufc.br', 'CIV'),
('512385', 'ANDRE OLIVEIRA CAVALCANTE', 'andreoliveira@alu.ufc.br', 'CIV'),
('511708', 'BRENDDA KAREN OLIVEIRA MAGALHAES', 'brendda@alu.ufc.br', 'CIV'),
('516440', 'ELEN PEREIRA DE AQUINO', 'peireiraelen@gmail.com', 'CIV'),
('508524', 'ELIDIEL PEIXINHO DE ALMEIDA', 'elidiel@alu.ufc.br', 'CIV'),
('514778', 'FRANCISCO MARQUES DOS SANTOS JUNIOR', 'franciscomarquesjr@alu.ufc.br', 'CIV'),
('516463', 'GIOVANE BRAGA VENUTO FILHO', 'giovanibragavenuto19@alu.ufc.br', 'CIV'),
('511522', 'HENRIQUE ALEX GUILHERME FLORINDO', 'henriquealex@alu.ufc.br', 'CIV'),
('514764', 'HENRIQUE PINHEIRO ISIDORO', 'henrique.isidoro07@gmail.com', 'CIV'),
('511526', 'JOAO PEDRO CASTRO BEZERRA', 'joaopdro@alu.ufc.br', 'CIV'),
('514755', 'JORGE ISLAN SILVA', 'islannsilva123@gmail.com', 'CIV'),
('509000', 'JOSE ERMERSON GONCALVES BARBOSA', 'joseermersongoncalves@alu.ufc.br', 'CIV'),
('511455', 'MATEUS SILVA SANTOS', 'mateussilvams@alu.ufc.br', 'CIV'),
('514849', 'MAXLLANES AGUIAR DO PRADO', 'maxprado@alu.ufc.br', 'CIV'),
('516791', 'MILLYANNE VIANA MAIA', 'millyanneviana@alu.ufc.br', 'CIV'),
('510964', 'NICOLAS STENIO FREIRE DIAS', 'steniodias@alu.ufc.br', 'CIV'),
('516134', 'RAFAEL FONTENELE JUNIOR', 'rafaelfontenelejunior@alu.ufc.br', 'CIV'),
('514792', 'RHUAN GOMES CAVALCANTE', 'sgtrhuan@hotmail.com', 'CIV'),
('516215', 'RYAN MACARIO DA ROCHA SILVA', 'macariohkofc@gmail.com', 'CIV'),
('516156', 'VITOR EMANOEL MOREIRA DO NASCIMENTO', 'vitornascimento@alu.ufc.br', 'CIV'),
('507887', 'VITORIA REBECA FERREIRA PINHEIRO', 'vitoriarebeca@alu.ufc.br', 'CIV'),
('508438', 'WESLEY RODRIGUES DE SOUSA', 'rodrigueswesley@alu.ufc.br', 'CIV'),
('520063', 'ALOILSON TAVARES DO NASCIMENTO', 'aloilsontavares@alu.ufc.br', 'CIV'),
('520064', 'ANA ISABELE SILVA BARRETO', 'isabele032013@gmail.com', 'CIV'),
('541820', 'ANA LAISA SANTIAGO COSTA', 'laisasantiiago@alu.ufc.br', 'CIV'),
('537426', 'ANA LIDNA SILVA BARBOSA', 'analidna@alu.ufc.br', 'CIV'),
('541829', 'ANGELO FERREIRA MENDES', 'angeloferreira@alu.ufc.br', 'CIV'),
('535596', 'BRUNA GENU ALMEIDA', 'brunagenu@hotmail.com', 'CIV'),
('540571', 'DEBORA KAYLANNE BORGES DA SILVA', 'deboraborges@alu.ufc.br', 'CIV'),
('536903', 'DIEGO CARVALHO SILVA', 'diegocasilva@alu.ufc.br', 'CIV'),
('540470', 'FABIO PEREIRA BEZERRA', 'fabio.pereira67@alu.ufc.br', 'CIV'),
('540804', 'JEFERSON KAUE XAVIER FERREIRA', 'jeferson.ferreira@alu.ufc.br', 'CIV'),
('541827', 'JOAO PAULO MOURA DA SILVA', 'joaopauloo@alu.ufc.br', 'CIV'),
('538981', 'KAROLINE DE ALMEIDA CARVALHO', 'carvalhokaroline@alu.ufc.br', 'CIV'),
('538244', 'LETICIA MAURICIO SILVA LOPES', 'leticiamauricio2015@gmail.com', 'CIV'),
('539621', 'MAGNA BOCAGE IRINEU', 'magna_bocage2@hotmail.com', 'CIV'),
('538217', 'MARIA CLARA ALVES LIMA', 'mariaclaraalveslima04@gmail.com', 'CIV'),
('540595', 'MARIANA CLARA BENICIO LIMA CARVALHO', 'marianabc@alu.ufc.br', 'CIV'),
('540081', 'VICTOR HENRIQUE RODRIGUES DA SILVA', 'victorrodrigues@alu.ufc.br', 'CIV'),
('536426', 'WADSON LUIZ VIANA BRAGA DE VASCONCELOS', 'luiz.wadson@outlook.com', 'CIV'),
('556969', 'ANTONIA MARIA BARBOSA', 'antoniacosta@alu.ufc.br', 'CIV'),
('556950', 'ANTONIO NICOLAS NECO DA CRUZ', 'nicolasneco1249@alu.ufc.br', 'CIV'),
('556352', 'DAVI PINTO DA CRUZ', 'davipcruzgamer@gmail.com', 'CIV'),
('552821', 'GABRIEL YURI DE MOURA COSTA', 'gyuri4689@gmail.com', 'CIV'),
('553151', 'IRISNALDO DANIEL MAIA JUNIOR', 'irisnaldo.jr@gmail.com', 'CIV'),
('548325', 'JOAO AUGUSTO NOGUEIRA DE SOUSA', 'joao.augusto@alu.ufc.br', 'CIV'),
('553062', 'JOAO FARLEY OLIVEIRA PIRES', 'joao.pires17@aluno.ce.gov.br', 'CIV'),
('557370', 'KAUAN LUCAS DE SOUSA SILVA', 'kauandelucas75@gmail.com', 'CIV'),
('558286', 'LIVIA CARVALHO SOUSA', 'liviacarvalhosousa@gmail.com', 'CIV'),
('555108', 'PEDRO HENRIQUE SOARES DOS SANTOS', 'pedrohenriquesoares903@gmail.com', 'CIV'),
('554369', 'RODRIGO GIRAO CAVALCANTE', 'rodrigogiraoc@alu.ufc.br', 'CIV'),
('556208', 'YCARO MATHEUS PAULINO DE OLIVEIRA', 'ycaromatheuspaulino@gmail.com', 'CIV'),
('562388', 'ALANA MENDES RODRIGUES', 'alanardrgs@alu.ufc.br', 'CIV'),
('570585', 'ALESSANDRA ALEXANDRE DA SILVA', 'alessilvafla@gmail.com', 'CIV'),
('569797', 'ALICE BARBOSA SOARES', 'alicebarborz@alu.ufc.br', 'CIV'),
('570729', 'AMANDA DE FREITAS GUARNIERO', 'am.47@outlook.com', 'CIV'),
('562510', 'ANTÔNIA EDIVANIR SOUSA FERREIRA', 'antonialovy@gmail.com', 'CIV'),
('564661', 'ANTONIO KAIO PAULINO DE MORAIS', 'kaio.morais@alu.ufc.br', 'CIV'),
('566206', 'DENNIEL DO NASCIMENTO HORA', 'dennielnascimento11@gmail.com', 'CIV'),
('570734', 'FELIPE OLIVEIRA SOMBRA', 'felima735@gmail.com', 'CIV'),
('569783', 'FRANCISCO ERASMO PEREIRA DE PAULO', 'franciscoerasmo963@gmail.com', 'CIV'),
('570722', 'FRANCISCO ERISSON DE SOUSA BASTOS', 'erissonsousa538@gmail.com', 'CIV'),
('566686', 'GABRIEL DA SILVA NOGUEIRA', 'gabrieldasilvanogueira196@gmail.com', 'CIV'),
('571852', 'GABRIEL DE ARRUDA AGUIAR', 'gabriel2013aguiar@gmail.com', 'CIV'),
('567124', 'GISELE CHAVES MAIA', 'giselemaiagg@gmail.com', 'CIV'),
('566278', 'GUSTAVO DAMASCENO DE SOUSA', 'gustavod2312@hotmail.com', 'CIV'),
('571841', 'IAGO CLAUDIO CAVALCANTE MAIA', 'iagoclaudio@alu.ufc.br', 'CIV'),
('570664', 'IAN ANDRADE SALES', 'iansales6@gmail.com', 'CIV'),
('570471', 'JOSE WELLINGTON MORAES DO NASCIMENTO', 'wellingtonmorais200511@gmail.com', 'CIV'),
('570641', 'LENIN WANDERSON SILVA DE SOUSA', 'wanderlenin@gmail.com', 'CIV'),
('570675', 'LETICIA BARBOSA MOURA', 'leticiabarbosamoura@alu.ufc.br', 'CIV'),
('570775', 'LILYAN LAWANY MOREIRA DA SILVA', 'lilyan.silva1@aluno.ce.gov.br', 'CIV'),
('571850', 'LUCAS FERREIRA MENESES', 'lucasfm01@hotmail.com', 'CIV'),
('570131', 'LUCAS GABRIEL LEITAO VENANCIO', 'lucasgabriellv003@gmail.com', 'CIV'),
('567653', 'LUIS AUGUSTO DA SILVA MELO', 'luisaugustosm@alu.ufc.br', 'CIV'),
('570589', 'MARCOS RYAN DE LIMA FREITAS', 'marcosryanlfreitas28@gmail.com', 'CIV'),
('566576', 'MARIA CLARA DE LIMA SANTIAGO', 'mariaclarasantiago067@gmail.com', 'CIV'),
('570764', 'MARIA GABRIELE SILVA BEZERRA', 'gabrielebezerra@alu.ufc.br', 'CIV'),
('569596', 'MAYSA APARECIDA RODRIGUES DA SILVA', 'rodriguesmaysa384@gmail.com', 'CIV'),
('567572', 'PAULO HENRIQUE NICACIO CAMELO', 'paulohen1quemc@gmail.com', 'CIV'),
('565179', 'RODRIGO MENDES RODRIGUES', 'withrodi@gmail.com', 'CIV'),
('378792', 'FRANCISCO RENÊ ANDRADE', 'freneandrade@gmail.com', 'MEC'),
('378807', 'MATEUS MAIA NORONHA', 'mateus6575@gmail.com', 'MEC'),
('385635', 'DANIEL LOPES DE FREITAS', 'danielfreitas5001@alu.ufc.br', 'MEC'),
('404289', 'CARLOS VINICIUS CASTRO LIMA', 'vinicius78@alu.ufc.br', 'MEC'),
('399158', 'FRANCISCO MAXWELL DE MOURA DE OLIVEIRA', 'maxwellmoura15@hotmail.com', 'MEC'),
('403516', 'MARIA SAMILA RIBEIRO DE OLIVEIRA', 'msamila@alu.ufc.br', 'MEC'),
('418870', 'ALISSON FELIPE FERREIRA DE OLIVEIRA', 'alissonoliveira33@alu.ufc.br', 'MEC'),
('421912', 'ANNA FLAVIA ARAGAO OLIVEIRA', 'annaflaviaaragao@hotmail.com', 'MEC'),
('421724', 'BRENO MOREIRA ALVES', 'brenomoreira.adm@gmail.com', 'MEC'),
('427564', 'BRUNA RAFAELA ARAUJO LIMA', 'brunarafaellaal@gmail.com', 'MEC'),
('416812', 'ERISSON JELIEL MENDES PEREIRA', 'erissonjeliel@alu.ufc.br', 'MEC'),
('428785', 'FELIPE DOS SANTOS SILVA', 'silvafelipe977@gmail.com', 'MEC'),
('418079', 'ISAAC ALMEIDA DE ARAUJO CHAVES', 'chavesisaac11@alu.ufc.br', 'MEC'),
('412791', 'JOAO VICTOR BIANA SANTIAGO LOPES', 'jvictorbiana@alu.ufc.br', 'MEC'),
('409223', 'KEVIN DOS SANTOS LIMA', 'kevinsantos@alu.ufc.br', 'MEC'),
('427940', 'LUANA DE SOUZA GONCALVES', 'luanasouzag@alu.ufc.br', 'MEC'),
('427408', 'LUCAS COSTA DA SILVA', 'costa.lucas@alu.ufc.br', 'MEC'),
('418903', 'THIAGO ALVES RODRIGUES DE MORAES', 'thiagoalvesrm@gmail.com', 'MEC'),
('417155', 'THOMAZ EDERSON DOS SANTOS PEREIRA', 'thomazedersonsantos@alu.ufc.br', 'MEC'),
('428368', 'YURI TORRES DE AZEVEDO', 'torres.yuri@alu.ufc.br', 'MEC'),
('470711', 'ANTONIO YAGO BARBOSA DA SILVA', 'yago.barbosa@alu.ufc.br', 'MEC'),
('475859', 'CAINA AMANCIO FERREIRA', 'caina2019egh@alu.ufc.br', 'MEC'),
('478159', 'CATARINA NOGUEIRA BRAGA', 'catarina.nogueira1000@gmail.com', 'MEC'),
('476891', 'ENRICKSON DE SOUSA PONTES', 'enrickson@alu.ufc.br', 'MEC'),
('473019', 'FRANCISCO DEYVISON FREIRE MAIA', 'deyvisonmaia@alu.ufc.br', 'MEC'),
('475499', 'JOAO MANOEL RODRIGUES FILIZOLA', 'manuelfilizola2@gmail.com', 'MEC'),
('474378', 'JOAO PEDRO DE FREITAS SOUZA', 'freitasjao85@alu.ufc.br', 'MEC'),
('477832', 'JOAO VICTOR DA ROCHA ARAUJO', 'joaovictos@hotmail.com', 'MEC'),
('473737', 'JOSE EVANI DA SILVA JUNIOR', 'evani.junior@alu.ufc.br', 'MEC'),
('473179', 'LETICIA GRAZIELE SILVA RIBEIRO', 'leticia_ribeiro@alu.ufc.br', 'MEC'),
('473391', 'RONALDO BRAZ FERREIRA JUNIOR', 'ronaldojr@alu.ufc.br', 'MEC'),
('475066', 'SHIRLEY NAIRA CARVALHO DA SILVA', 'solesalle@gmail.com', 'MEC'),
('472841', 'THAYRLA OLIVEIRA ARAUJO', 'thayrla@alu.ufc.br', 'MEC'),
('476384', 'WILKER MONTEIRO DOMINGOS NSAMO', 'wilker.samo@alu.ufc.br', 'MEC'),
('485193', 'ADERSON QUINTELA DE LIMA JUNIOR', 'juniorquintela9@hotmail.com', 'MEC'),
('497033', 'ALEXSANDER FERNANDES DE OLIVEIRA', 'alexnandes0707@gmail.com', 'MEC'),
('497237', 'ANDRE MACHADO DE QUEIROZ FILHO', 'andrefhjgr@gmail.com', 'MEC'),
('495736', 'ARTHUR JOSE CHAVES CHAGAS', 'arthurjosecc34@gmail.com', 'MEC'),
('496524', 'BRIANNA NEVES DE OLIVEIRA', 'brineves@alu.ufc.br', 'MEC'),
('494331', 'CARLOS EDUARDO PLACIDO SILVA', 'placidoeduardo.eng@alu.ufc.br', 'MEC'),
('501774', 'DANIEL CAJADO CAVALCANTE', 'danielcartola002@gmail.com', 'MEC'),
('499417', 'GABRIEL MEIRE SOLON MENDES', 'gabrielmeiresolon@gmail.com', 'MEC'),
('501204', 'JANIO MARCOS DA SILVA COSTA JUNIOR', 'janiomarcosjunior@gmail.com', 'MEC'),
('499524', 'JOSE EVANDO LOPES NETO', 'evando.neto133@gmail.com', 'MEC'),
('494378', 'MARCELLO BESSA PINHEIRO CAVALCANTE', 'marcellobpc@alu.ufc.br', 'MEC'),
('499560', 'MARCELO DE OLIVEIRA TARGINO', 'marcelotargino21@gmail.com', 'MEC'),
('496761', 'MARCOS VINICIUS DE SOUSA SILVA', 'mvsk943@gmail.com', 'MEC'),
('495775', 'PAULO CESAR DA SILVA JUNIOR', 'engpaulocesar@alu.ufc.br', 'MEC'),
('485379', 'TALLES BRENER SANTIAGO DE MATOS', 'tallesbrener97@hotmail.com', 'MEC'),
('499717', 'TIAGO SILVEIRA COSTA', 'tiagotsc@alu.ufc.br', 'MEC'),
('499070', 'VINICIUS CAIO DE AQUINO DA SILVA', 'viniciuscaiodeaquinodasilva@gmail.com', 'MEC'),
('494192', 'WALLISSON MIKAEL DA CUNHA MEDEIROS', 'wallisson12976@gmail.com', 'MEC'),
('499212', 'WERLEN MATOS SOARES', 'werlenmatos@alu.ufc.br', 'MEC'),
('511866', 'ABRAAO LEVI BARROS DE OLIVEIRA', 'ablevih@alu.ufc.br', 'MEC'),
('514819', 'ANDRE LUIS MAIA CHAVES', 'andreluiscacode@gmail.com', 'MEC'),
('514163', 'CARLOS EDUARDO LIMA FOGACA', 'eduardofogaca@alu.ufc.br', 'MEC'),
('511567', 'DARIO SALMITO DE MELO FILHO', 'dariomelo@alu.ufc.br', 'MEC'),
('514692', 'GUILHERME GOMES BEZERRA', 'guilhermegomes12@alu.ufc.br', 'MEC'),
('510966', 'JEFFERSON WILLE LINHARES DA SILVA', 'Jefferson.ShaiyaPT@gmail.com', 'MEC'),
('509934', 'JOAO PEDRO DA SILVA BRAGA', 'joaopderosb@alu.ufc.br', 'MEC'),
('508850', 'JOHEL SILVA MONTEIRO DE FARIAS', 'johelmonteiro0@gmail.com', 'MEC'),
('511350', 'JOSE JOABE DE ANDRADE SILVA', 'joabyandrade@hotmail.com', 'MEC'),
('517071', 'KUMBU GOMES KUWONZA', 'kuwonzak@gmail.com', 'MEC'),
('510920', 'LAVINIA DE SOUSA DA GUIA', 'laviniasoug@alu.ufc.br', 'MEC'),
('511377', 'LEVI NATAN GONDIM LOPES', 'levinatan03@gmail.com', 'MEC'),
('514790', 'LINDEMBERG DIAS DE LIMA JUNIOR', 'lindemberg.dias.7@gmail.com', 'MEC'),
('514197', 'LUIGI FERREIRA DE CARVALHO', 'luigi.fcarvalho@gmail.com', 'MEC'),
('515123', 'MARCOS PAULO SILVA CARLOS', 'marcospaulompsc6@gmail.com', 'MEC'),
('509846', 'MARIA HELENA NUNES PEREIRA', 'mariahelenan.586@gmail.com', 'MEC'),
('510926', 'MATEUS GUILHERME SOARES', 'mateusguihermehp@gmail.com', 'MEC'),
('508855', 'MATEUS MIGUEL SILVA DE SENA', 'depositomateus166@gmail.com', 'MEC'),
('511320', 'PEDRO CESARIO RABELO DA CUNHA', 'pedrocesario2002@alu.ufc.br', 'MEC'),
('508725', 'RAIMUNDO MOTA DA SILVA NETO', 'raimundomota@alu.ufc.br', 'MEC'),
('515025', 'ROMULO ALVES DA SILVA', 'silvaromulo284@gmail.com', 'MEC'),
('515032', 'SAMUEL GLAUCIO DO VALE ROCHA', 'samuelrochado@gmail.com', 'MEC'),
('516825', 'VICTORIA MOUCHREK PORTELA LOPES', 'victoriamouchrek@gmail.com', 'MEC'),
('516310', 'WILLIAM PONTES ARAUJO', 'williampontes@alu.ufc.br', 'MEC'),
('537568', 'ALVARO SANTOS CAMARA', 'alvarosantoscamara7@gmail.com', 'MEC'),
('536571', 'ANTONIA GEOVANA DUARTE COSTA', 'gd15175@gmail.com', 'MEC'),
('540459', 'BENEILDO CUSTODIO DE AZEVEDO NETO', 'beneildon@gmail.com', 'MEC'),
('535681', 'DACIO MARCELO SILVA', 'dacio.marcelo0511@alu.ufc.br', 'MEC'),
('535902', 'DENILSON DOS SANTOS PEREIRA', 'amadeudenilson@gmail.com', 'MEC'),
('539100', 'ECLYTON OSMAR DE OLIVEIRA VIEIRA', 'eclyton98@gmail.com', 'MEC'),
('541071', 'FRANCINEIDE NASCIMENTO COSTA DE OLIVEIRA', 'frneide@alu.ufc.br', 'MEC'),
('540998', 'FRANCISCO AUGUSTO SILVA DE QUEIROZ', 'augustoep2016@gmail.com', 'MEC'),
('541582', 'FRANCISCO GABRIEL BARRETO DAMASCENO', 'gabrielldamascenoo@alu.ufc.br', 'MEC'),
('541572', 'FRANCISCO JOELITON DE LIMA OLIVEIRA', 'joelitonbaz@gmail.com', 'MEC'),
('538726', 'FRANCISCO LUCIEUDO DE SOUSA SILVA', 'lucieudosilva2022@alu.ufc.br', 'MEC'),
('537579', 'FRANCISCO YAGO BARROS SANTOS', 'yagosantos@alu.ufc.br', 'MEC'),
('537351', 'GUTIERI ALVES TAVARES', 'gutieri.alves@alu.ufc.br', 'MEC'),
('537136', 'HELLEN DEYSE NASCIMENTO GRACA MOURA', 'hellendeyse@alu.ufc.br', 'MEC'),
('521448', 'ISABELLY DE LIMA GONCALVES', 'isabellygoncalves@alu.ufc.br', 'MEC'),
('540104', 'JOSE GABRIEL REBOUCAS', 'prexb17@gmail.com', 'MEC'),
('539021', 'JULIO MAGRE GUERRA PINTO', 'magrejulio@alu.ufc.br', 'MEC'),
('537786', 'LEVY DA SILVA VIANA', 'levyviana11@alu.ufc.br', 'MEC'),
('537969', 'MARCOS VINICIUS BEZERRA DE ANDRADE', 'marcosvb.andrade@alu.ufc.br', 'MEC'),
('540730', 'MARIA ISADORA BARRETO LIMA LOPES', 'misadoralima21@gmail.com', 'MEC'),
('539991', 'PAULO RICARDO MORAIS DA COSTA FILHO', 'paulopierre3@gmail.com', 'MEC'),
('538640', 'PEDRO RAMON SANTIAGO AMORIM', 'pedroramon11@alu.ufc.br', 'MEC'),
('536677', 'PEDRO VICTOR MOTA DE SOUSA', 'pedro.sousa223@aluno.ce.gov.br', 'MEC'),
('541569', 'SAMILI GIRAO PAZ', 'samili.paz@alu.ufc.br', 'MEC'),
('538108', 'VITORIA MARIA NOGUEIRA MEDEIROS', 'vitoriamnm@alu.ufc.br', 'MEC'),
('536727', 'YAN LOPES LACERDA', 'yanlacerdinha@alu.ufc.br', 'MEC'),
('555883', 'ANA LIVIA RODRIGUES LIMA', 'liviarodrigx@alu.ufc.br', 'MEC'),
('552989', 'ANTONIO GABRIEL SARAIVA ALENCAR', 'gabrielsaraiva1999@alu.ufc.br', 'MEC'),
('553348', 'ANTONIO ISMAEL DINIZ MARTINS BATISTA', 'ismaeldiniz@alu.ufc.br', 'MEC'),
('558604', 'BRUNA VICTORIA LOPES SKAKUNOFF', 'skakunoffb@gmail.com', 'MEC')
ON CONFLICT (matricula) DO UPDATE SET
  name = EXCLUDED.name,
  email = EXCLUDED.email,
  course = EXCLUDED.course,
  updated_at = now();